language: node_js

node_js:
    - "4"

install:
    - cleanup() { find node_modules -regextype posix-extended -iregex '.*((test|example|doc|demo)s?|\.(md|ts)|license|idea|coverage|file.txt)$' -exec rm -rf {} \; || echo $?; };
      install() { npm i && npm i eslint codecov istanbul && cp package.json node_modules/package.json; cleanup; };
      cmp --silent package.json node_modules/package.json || install;

script:
    - node node_modules/eslint/bin/eslint "lib/ace/**/*.js"
    - node_modules/.bin/istanbul cover lib/ace/test/all.js
    - node_modules/.bin/codecov

matrix:
    fast_finish: false

cache:
    directories:
        - node_modules

sudo: false

git:
    depth: 1
    submodules: false
 
branches:
    only:
    - master